---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/services

- Archive Media Apps:
    - Sonarr - Archive:
        icon: sonarr.png
        href: https://sonarr.crzynet.com
        widget:
          type: sonarr
          fields: ["wanted", "queued", "series"]
          url: https://sonarr.crzynet.com
          key: {{HOMEPAGE_VAR_SONARR_API}}
          #enableQueue: true
    - Radarr - Archive:
        icon: radarr.png
        href: https://radarr.crzynet.com
        widget:
          type: radarr
          fields: ["wanted", "queued", "movies"]
          url: https://radarr.crzynet.com
          key: {{HOMEPAGE_VAR_RADARR_API}}
          enableQueue: true
    - Prowlarr - Archive:
        icon: prowlarr.png
        href: https://prowlarr.crzynet.com
        widget:
          type: prowlarr
          fields: ["numberOfGrabs", "numberOfQueries", "numberOfFailGrabs"]
          url: https://prowlarr.crzynet.com
          key: {{HOMEPAGE_VAR_PROWLARR_API}}
    - Plex - Archive:
        icon: plex.png
        href: https://plex.tv
        widget:
          type: plex
          url: http://plexserver01.home.arpa:32400
          key: {{HOMEPAGE_VAR_PLEX_TOKEN}}
    - OMBI - Archive:
        icon: ombi.png
        href: http://ombi.home.arpa
        widget:
          type: ombi
          url: http://ombi.home.arpa
          key: {{HOMEPAGE_VAR_OMBI_API}}
    - Overseerr - Archive:
        icon: overseerr.png
        href: http://overseerr.home.arpa  
        widget:
          type: overseerr
          url: http://overseerr.home.arpa
          key: {{HOMEPAGE_VAR_OVERSEER_API}}
    - ruTorrent - Luna:
        icon: rutorrent.png
        href: https://crzykidd.luna.usbx.me/rutorrent/ 
        widget:
          type: rutorrent
          url: https://crzykidd.luna.usbx.me/rutorrent/
          username: {{HOMEPAGE_VAR_RUTORRENT_USER}}
          password: {{HOMEPAGE_VAR_RUTORRENT_PASSWORD}}
    - Cloudflared:
        icon: cloudflare.png
        href: https://dash.cloudflare.com/
        widget:
          type: cloudflared
          accountid: {{HOMEPAGE_VAR_CLOUDFLARE_ACCOUNTID}}
          tunnelid: {{HOMEPAGE_VAR_CLOUDFLARE_TUNNELID}}
          key: {{HOMEPAGE_VAR_CLOUDFLARE_API_TOKEN}}
    - Syncthing:
        icon: syncthing.png
        href: https://syncthing.crzynet.com/
        #widget:
        #  type: strelaysrv
        #  url: http://syncthing01.home.arpa:8384
    - Kavita:
        icon: kavita.png
        href: http://kavita.home.arpa/home/
    - Lidarr:
        icon: lidarr.png
        href: https://lidarr.crzynet.com
        widget:
            type: lidarr
            url: https://lidarr.crzynet.com
            key: {{HOMEPAGE_VAR_LIDARR_KEY}}
            

- Servers:
    - PVE01: 
       icon: proxmox.png
       description: PVE 01 Server
       href: https://pve01.home.arpa:8006/
    - PVE02: 
        icon: proxmox.png
        description: PVE 01 Server
        href: https://pve02.home.arpa:8006/
    - PVENAS01: 
       icon: proxmox.png
       description: PVENAS 01 Server
       href: https://pvenas01.home.arpa:8006/
    - PBS: 
        icon: proxmox.png
        description: ProxMox Backup Server
        href: https://pbs.home.arpa:8007/
- Docker:
    - Komodo-docker50:
        icon: komodo.png
        href: https://komodo.crzynet.com
        description: Komodo Docker Manger
    - Portainer-docker40:
        icon: portainer.png
        href: http://portainer.crzynet.com
        description: Portainer Docker40 environemnt
        # Widget is broken in Portainer 2 with K8s
        widget:
          type: portainer
          url: https://portainer.crzynet.com
          env: 2
          key: {{HOMEPAGE_VAR_PORTAINER_40}}
    - Traefik - docker50:
        icon: traefik.png
        href: https://docker50.crzynet.com/dashboard
        widget:
            type: traefik
            url: https://docker50.crzynet.com
- Home Automation/Reporting:
    - nodered:
        icon: node-red.png
        href: http://nodered.crzynet.com/
    - grafana:
        icon: grafana.png
        href: http://grafana.home.arpa/
        widget:
          type: grafana
          url: http://grafana.home.arpa/
          username: {{HOMEPAGE_VAR_GRAFANA_USERNAME}}
          password: {{HOMEPAGE_VAR_GRAFANA_PASSWORD}}
    - zwave-js-ui:
        icon: zwavejsui.png
        href: https://zwavejsui.home.arpa:8091/
    - phpmyadmin:
        icon: phpmyadmin.png
        href: https://phpmyadmin.crzynet.com/

- Solar Info:
    - Solar-Assistant:
        icon: solar.png
        href: http://solar-assistant.home.arpa/
    - EG4 Monitor:
        icon: solar.png
        href: https://monitor.eg4electronics.com/WManage/web/monitor/inverter   
- Network:
    - Technitium - dns01:
        icon: technitium.png
        href: http://dns01.home.arpa:5380
        widget:
            type: technitium
            url: http://dns01.home.arpa:5380
            key: {{HOMEPAGE_VAR_DNS01}}   
            range: LastDay # optional, defaults to LastHour
    - Technitium - dns02:
        icon: technitium.png
        href: http://dns02.home.arpa:5380
        widget:
            type: technitium
            url: http://dns02.home.arpa:5380
            key: {{HOMEPAGE_VAR_DNS02}}   
            range: LastDay # optional, defaults to LastHour            
    - Technitium - dns03:
        icon: technitium.png
        href: http://dns03.home.arpa:5380
        widget:
            type: technitium
            url: http://dns03.home.arpa:5380
            key: {{HOMEPAGE_VAR_DNS03}}   
            range: LastDay # optional, defaults to LastHour            
    - Portainer-k3s:
        icon: portainer.png
        href: http://portainer.home.arpa
        description: Portainer k3s cluster
        #Widget is broken in Portainer 2 with K8s
        #widget:
        #  type: portainer
        #  url: http://portainer.home.arpa
        #  env: 1
        #  key: {{HOMEPAGE_VAR_PORTAINER_K3S_API}}


    


- Storage:
    - tnas01:
        icon: truenas.png
        href: https://tnas01.home.arpa
        widget:
          type: truenas
          url: https://tnas01.home.arpa
          username: {{HOMEPAGE_VAR_TNAS01_USERNAME}}
          password: {{HOMEPAGE_VAR_TNAS01_PASSWORD}}

    - FS01 - SSD:
        icon: synology.png
        href: https://fs01.home.arpa:5001
        widget:
          type: diskstation
          url: https://fs01.home.arpa:5001
          username: {{HOMEPAGE_VAR_FS02_USERNAME}}
          password: {{HOMEPAGE_VAR_FS02_PASSWORD}}
    - FS02 - Spindle:
        icon: synology.png
        href: https://fs02.home.arpa:5001
        widget:
          type: diskstation
          url: https://fs02.home.arpa:5001
          username: {{HOMEPAGE_VAR_FS02_USERNAME}}
          password: {{HOMEPAGE_VAR_FS02_PASSWORD}}
    
   
- K8s Tools:
    - Traefik - k3s-01:
        icon: traefik.png
        href: http://traefik.home.arpa/dashboard/
        widget:
            type: traefik
            url: http://traefik.home.arpa

    - Longhorn Dashboard:
        icon: longhorn.png
        href: http://longhorn.home.arpa
    - Keel Dashboard:
        icon: kubernetes.png
        href: http://keel.home.arpa

- IPMI:
    - docker10 IPMI:
        icon: supermicro.png
        href: http://192.168.51.240
    - pve01-IPMI:
        icon: supermicro.png
        href: http://192.168.51.241
    - pvenas01-IPMI:
        icon: supermicro.png
        href: http://192.168.51.242
    - pvenas02-IPMI:
        icon: hp.png
        href: http://192.168.51.243

- 3D Printing:
    - Spoolman:
        icon: spoolman.png
        href: https://spoolman.crzynet.com
#        widget:
#            type: spoolman
#            url: https://spoolman.crzynet.com
    - Octoprint:
        icon: octoprint.png
        href: http://octopi.home.arpa/#control
        widget:
            type: octoprint
            url: http://octopi.home.arpa
            key: {{HOMEPAGE_VAR_OCTOPI_KEY}}
    - Manyfold:
        icon: manyfold.png
        href: https://manyfold.crzynet.com

