---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/settings

title: CrzyNet Homepage
fiveColumns: true
providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
  longhorn:
    url: http://longhorn.home.arpa

layout:
  #Network:
  #  style: column
  #  columns: 5
  Archive Media Apps:
    style: row
    columns: 5